version: "3"
services:
  mongodb:
    build:
      context: ./mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
  datacollector:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      - DATABASE=dev
      - URI=mongodb://mongodb:27017/dev
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=local
      - MAILBOX=the-useless-box@mail.ru
      - MAIL_PASS=^TmtyprT3MR3
networks:
  backend: