spring:
  data:
    mongodb:
      database: ${DATABASE}
      uri: ${URI}
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAILBOX}
    password: ${MAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, datacollector
  endpoint:
    health:
      show-details: always
data-collector:
  serverEmail: ${MAILBOX}
server:
  port: ${PORT}