spring:
  data:
    mongodb:
      database: ${DATABASE}
      uri: ${URI}
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAILBOX}
    password: ${MAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  port: ${PORT}